name: Build using .NET Core

on:
  push:
    branches: dev
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1

      - name: Install dependencies
        run: dotnet restore

      - name: Build Discord.Net
        run: dotnet build --no-restore --configuration Release

      - name: Pack Discord.Net
        run: |
            NOW=$(date +%Y%m%d%H%M%S)
            dotnet pack --no-build --configuration Release --include-source --include-symbols --version-suffix dev-yeba-$NOW
            dotnet pack src/Discord.Net/Discord.Net.csproj --configuration Release /p:VersionSuffix=-yeba-$NOW

      - name: Push generated package to GitHub registry
        run: |
            dotnet nuget add source 'https://pkgs.dev.azure.com/Yeba/DustyBot/_packaging/Dependencies/nuget/v3/index.json' --name azure --username ${{secrets.AZURE_USER}} --password ${{secrets.AZURE_PKG_PUBLISH_PAT}} --store-password-in-clear-text
            dotnet nuget push src/**/*.nupkg -s azure -k az --skip-duplicate
